### ISSUE TITLE
Dissolution Chamber recipes don't work

### ISSUE THREAD

**Issue by SheReyy** [Mrthomas20121-Mods/ForegoingTweaker#1]
I tried this script:

DissolutionChamberRecipe.addRecipe("test", [<item:minecraft:stick>, <item:minecraft:carrot>], <fluid:minecraft:water> * 1000, 20, <item:minecraft:golden_carrot>);

It does not work, I get this error:
![2021-10-19_18 29 07](https://user-images.githubusercontent.com/91336389/137943233-7f924a6b-5908-4315-b12a-33a10cb763a4.png)

**Comment by Mrthomas20121** [comment]
don't use the class directly. use the recipe type(granted there is no examples).
this is the example i tested in dev : 
```zs
<recipetype:industrialforegoing:dissolution_chamber>.addRecipe("example", [<item:minecraft:stone>, <item:minecraft:andesite>], <fluid:water>*1000, 2, <item:minecraft:dirt>);
 ```
