### ISSUE TITLE
no recipe for frames past pity frame

### ISSUE THREAD

**Issue by lipidconcentrategaming** [Mrthomas20121-Mods/ForegoingTweaker#3]
All the recipes for the other machine frames don't show like for example the supreme machine casing. We are on the latest version of jei on 1.18.2.

**Comment by Mrthomas20121** [comment]
that's a jei issue not caused by my mod. downgrade to jei 9. jei 10 changed stuff and broke many mods

**Comment by lipidconcentrategaming** [comment]
Okay, thank you very much.
