### ISSUE TITLE
The Laser Drill recipes do not work on 1.19.2

### ISSUE THREAD

**Issue by FerretWithACatHat** [Mrthomas20121-Mods/ForegoingTweaker#5]
I don't know why, if its related to Vars or if its an issue on your end, but trying to make a laser drill recipe comes up with a "No such member: addBiomeDictToBlacklist" error or similar.

**Comment by Mrthomas20121** [comment]
it was removed, you need to use the individual methods(addBiomeToWhitelist and addBiomeToBlacklist)
